stages:
  - test

.test:
  stage: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest tests/ -v

test:python3.6:
  extends: .test
  image: python:3.6

test:python3.7:
  extends: .test
  image: python:3.7

test:python3.8:
  extends: .test
  image: python:3.8

test:python3.9:
  extends: .test
  image: python:3.9

test:python3.10:
  extends: .test
  image: python:3.10

test:python3.11:
  extends: .test
  image: python:3.11

test:python3.12:
  extends: .test
  image: python:3.12

test:python3.13:
  extends: .test
  image: python:3.13

